import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-insurance-broker-commission-reconciliation",
  "engine": "recovery",
  "title": "Insurance Broker Commission Reconciliation",
  "shortTitle": "Broker Commission Recovery",
  "tagline": "Reconcile written, earned, contingent, and override commissions to carrier statements",
  "industry": "Insurance Distribution Finance",
  "uiPort": 4562,
  "apiPort": 5562,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Every earned broker commission identified, invoiced, and collected",
  "valueNarrative": "Connect producer and carrier agreements, policies, endorsements, premium transactions, cancellations, statements, and cash.",
  "calculation": {
    "actualKey": "paidCommission",
    "expectedKey": "earnedCommission",
    "actualLabel": "Carrier paid commission",
    "expectedLabel": "Broker earned commission",
    "varianceLabel": "Potential commission recovery",
    "direction": "expected-minus-actual",
    "finding": "Policy, premium, agreement, and carrier-statement evidence indicate unpaid broker commission.",
    "actions": [
      "Reconcile policies and premium transactions to statements",
      "Apply effective commission, override, and contingent terms",
      "Resolve cancellations, return premium, and producer splits",
      "Bill or dispute and reconcile carrier cash"
    ]
  }
},[
feature("carrier-and-producer-agreement-library","BCR01","Carrier and producer agreement library","Reconcile carrier and producer agreement library using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed carrier and producer agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("policy-and-endorsement-ingestion","BCR02","Policy and endorsement ingestion","Reconcile policy and endorsement ingestion using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed policy and endorsement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("written-premium-reconciliation","BCR03","Written premium reconciliation","Reconcile written premium reconciliation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed written premium reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("earned-premium-calculation","BCR04","Earned premium calculation","Reconcile earned premium calculation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed earned premium calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("base-commission-calculation","BCR05","Base commission calculation","Reconcile base commission calculation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed base commission calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("override-and-bonus-calculation","BCR06","Override and bonus calculation","Reconcile override and bonus calculation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed override and bonus calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("contingent-commission-forecasting","BCR07","Contingent commission forecasting","Reconcile contingent commission forecasting using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed contingent commission forecasting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("cancellation-and-return-commission","BCR08","Cancellation and return commission","Reconcile cancellation and return commission using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed cancellation and return commission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("producer-split-validation","BCR09","Producer split validation","Reconcile producer split validation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed producer split validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("direct-bill-statement-reconciliation","BCR10","Direct-bill statement reconciliation","Reconcile direct-bill statement reconciliation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed direct-bill statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("agency-bill-reconciliation","BCR11","Agency-bill reconciliation","Reconcile agency-bill reconciliation using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed agency-bill reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("missing-commission-detection","BCR12","Missing commission detection","Reconcile missing commission detection using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed missing commission detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("carrier-inquiry-and-dispute","BCR13","Carrier inquiry and dispute","Reconcile carrier inquiry and dispute using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed carrier inquiry and dispute decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("cash-application-and-aging","BCR14","Cash application and aging","Reconcile cash application and aging using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed cash application and aging decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]}),
feature("carrier-and-producer-profitability-analytics","BCR15","Carrier and producer profitability analytics","Reconcile carrier and producer profitability analytics using carrier and producer agreements, policy transactions, premium, endorsements, cancellations, statements, overrides, and cash receipts.","Produce a governed carrier and producer profitability analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["carrier","Carrier","text","Summit Specialty Insurance"],["statementPeriod","Statement Period","text","2026-06"],["paidCommission","Carrier Paid Commission","currency",742000],["earnedCommission","Broker Earned Commission","currency",886500]],{amountField:"paidCommission",subjects:["Commercial package book","Employee benefits book","Wholesale placement","Specialty program","Contingent commission year"]})
]);
